apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80  # External Port
      targetPort: 3000  # Port your app is listening on
      nodePort: 30007  # NodePort (use a port in the 30000-32767 range)
  type: NodePort
